spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://ohs0407.iptime.org:3306/Trash_can
    username: ks0689
    password: aksl4224

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  jwt:
    secret: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

logging:
  level:
    org.hibernate.sql : debug

cloud:
  aws:
    s3:
      bucket: "havebin"
    credentials:
      access-key: "AKIAW3MEDHH4OHC63SFH"
      secret-key: "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"
    region:
      static: "ap-northeast-2"
      auto: false
    stack:
      auto: false



